//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Add
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Add()
        {
            this.AgriculturalVehicles = new HashSet<AgriculturalVehicle>();
            this.ConstructionVehicles = new HashSet<ConstructionVehicle>();
            this.PassengerVehicles = new HashSet<PassengerVehicle>();
            this.RealEstates = new HashSet<RealEstate>();
            this.TransportationVehicles = new HashSet<TransportationVehicle>();
        }
    
        public int AddId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string Category { get; set; }
        public string Status { get; set; }
        public string State { get; set; }
        public string District { get; set; }
        public string Mandal { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string SubCategory { get; set; }
        public string NearestArea { get; set; }
        public string Remarks { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgriculturalVehicle> AgriculturalVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConstructionVehicle> ConstructionVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerVehicle> PassengerVehicles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RealEstate> RealEstates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransportationVehicle> TransportationVehicles { get; set; }
    }
}
