//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dataquotumEntities : DbContext
    {
        public dataquotumEntities()
            : base("name=dataquotumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Add> Adds { get; set; }
        public virtual DbSet<AgriculturalVehicle> AgriculturalVehicles { get; set; }
        public virtual DbSet<ConstructionVehicle> ConstructionVehicles { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<PassengerVehicle> PassengerVehicles { get; set; }
        public virtual DbSet<RealEstate> RealEstates { get; set; }
        public virtual DbSet<TransportationVehicle> TransportationVehicles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
